version: '3'
services:
  supersummariser:
    image: 'tomsaleeba/supersummariser'
    ports:
      - '5000:80'
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:somepass@pg/supersummariser
      ERSA_AUTH_TOKEN: replace-with-your-token # replace me!!!
  pg:
    image: 'postgres:10.2'
    environment:
      POSTGRES_PASSWORD: somepass
    volumes:
      - './pg_db/sql-init:/docker-entrypoint-initdb.d'
