"""empty message

Revision ID: 7a9b2f5d95d2
Revises: 2940ffe55dfe
Create Date: 2018-04-02 13:46:22.893373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9b2f5d95d2'
down_revision = '2940ffe55dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nova_flavor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flavor_id', sa.String(length=128), nullable=True),
    sa.Column('vcpus', sa.Integer(), nullable=True),
    sa.Column('ephemeral', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('ram', sa.Integer(), nullable=True),
    sa.Column('disk', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('openstack_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nova_flavor')
    # ### end Alembic commands ###
