"""empty message

Revision ID: da2c714afc6f
Revises: 7a9b2f5d95d2
Create Date: 2018-04-02 15:31:24.959575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da2c714afc6f'
down_revision = '7a9b2f5d95d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nectar_usage', sa.Column('biller', sa.String(length=128), nullable=True))
    op.add_column('nectar_usage', sa.Column('managerunit', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nectar_usage', 'managerunit')
    op.drop_column('nectar_usage', 'biller')
    # ### end Alembic commands ###
