"""empty message

Revision ID: e6f47bb7d5c5
Revises: da2c714afc6f
Create Date: 2018-04-02 21:47:53.015172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f47bb7d5c5'
down_revision = 'da2c714afc6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('openstack_project_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'openstack_project_id')
    # ### end Alembic commands ###
